[2021-01-07 20:52:25 +0000] [256] [INFO] Starting gunicorn 19.6.0
[2021-01-07 20:52:25 +0000] [256] [INFO] Listening at: http://127.0.0.1:8000 (256)
[2021-01-07 20:52:25 +0000] [256] [INFO] Using worker: sync
[2021-01-07 20:52:25 +0000] [259] [INFO] Booting worker with pid: 259
[2021-01-07 20:52:25 +0000] [259] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named 'ask.wsgi'
[2021-01-07 20:52:25 +0000] [259] [INFO] Worker exiting (pid: 259)
[2021-01-07 20:52:25 +0000] [256] [INFO] Shutting down: Master
[2021-01-07 20:52:25 +0000] [256] [INFO] Reason: Worker failed to boot.
[2021-01-07 20:54:03 +0000] [336] [INFO] Starting gunicorn 19.6.0
[2021-01-07 20:54:03 +0000] [336] [INFO] Listening at: http://127.0.0.1:8000 (336)
[2021-01-07 20:54:03 +0000] [336] [INFO] Using worker: sync
[2021-01-07 20:54:03 +0000] [339] [INFO] Booting worker with pid: 339
[2021-01-07 20:54:03 +0000] [339] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named 'ask.wsgi'
[2021-01-07 20:54:03 +0000] [339] [INFO] Worker exiting (pid: 339)
[2021-01-07 20:54:03 +0000] [336] [INFO] Shutting down: Master
[2021-01-07 20:54:03 +0000] [336] [INFO] Reason: Worker failed to boot.
